### ISSUE TITLE
custom use case paper2code.com / turnkey docker-compose

### ISSUE THREAD

**Issue by ghost** [orion-search/orion#152]
Hi @kstathou ,

Hope you are all well !

Quoting the about page, "If you plan to reuse Orion in your projects, let us know what you’re up to!", I wanted to check with you a couple of points.

For my part, I am developing a search engine for papers and their related implementation in terms of code. It is called https://paper2code.com. 

In a nutshell, I aggregate all meta informations available on a paper (eg. https://paper2code.com/paper/164402/image-super-resolution-with-cross-scale-non-local-attention-and-exhaustive-self-exemplars-mining), from 50 web sources, for doing faceted search (https://paper2code.com/search/papers?q=lecun) or create real-time alerts like on google alert. 

The goal is to create something between google scholar and google alerts on papers and code.

It is still a WIP as I try to implement as much as possible sub-components related to neural search, text similarity for abstracts,...

So I was wondering if you could highlight me on the following questions about Orion project:
- Is there any turnkey docker-compose to bootstrap the Orion project for a local test ?
- Can I integrate Orion project to paper2code ? If yes, what would you advise to make it simple ?
- Do you provide an api for the search side ? Is there any documentation ?
- Is Orion GPU or Multi-GPU enabled ?

Thanks in advance for your insights and inputs on these questions.

My twitter account is https://twitter.com/x0rzkov

So for not polluting this thread, it would be maybe easier to DM each other.

Wish you a great day ! Thanks again for this great project !

Cheers,
X

**Comment by kstathou** [comment]
Hi @x0rzkov,

Thanks for getting in touch, [papers2code](https://paper2code.com/) looks neat! This might be interesting to others so I'm responding here for completeness and we can continue with DMs. 

## Is there any turnkey docker-compose to bootstrap the Orion project for a local test?
I'm currently not using turnkey. You can run the Airflow DAG locally for testing. Have a look at this [tutorial](https://docs.orion-search.org/docs/running_etl)

## Can I integrate Orion project to paper2code ? If yes, what would you advise to make it simple?
Go for it and please do give credit where appropriate :) If you're using Airflow, it should be straightforward to integrate Orion for the collection, enrichment and analysis of academic documents from [Microsoft Academic Graph](https://www.microsoft.com/en-us/research/project/academic-knowledge) (MAG). 

An example based on what I've seen in `paper2code`: With Orion, you could collect all of the documents from MAG that contain the field of study `machine learning`, geocode the author affiliations, infer vectors for each paper abstract and build a Faiss index. This would populate your [left side panel](https://paper2code.com/search/papers?q=nlp) and create the components of a vector-based search engine. You can find the Airflow operators I've developed [here](https://docs.orion-search.org/docs/Operators). 

In the medium term, I would like to develop an API for Orion's ETL to simplify the integration with other services. Happy to hear your thoughts on this.

## Do you provide an api for the search side ? Is there any documentation ?
Currently, no. Do you think there's a use case for a search API? 

The [search engine](https://github.com/orion-search/search-engine) currently has two modes: 
- Keyword search: We use Elasticsearch to do a full-text search over the paper titles, abstracts and fields of study.
- Vector-based search: We transform abstracts to vectors with [sentence transformers](https://github.com/UKPLab/sentence-transformers) and build a Faiss index. Each new query is encoded with the same transformer model and passed onto the pre-built index for similarity matching. 

I'm developing a documentation site [here](https://docs.orion-search.org/). I will write about our work on the search engine and add a tutorial by the end of August.

## Is Orion GPU or Multi-GPU enabled ?
No :(

The [text2vector](https://github.com/orion-search/orion/blob/dev/orion/core/dags/orion.py#L211-L216) task would benefit from running on a GPU. Since I am using a pretrained model for the inference, I wonder if it would be faster and cheaper to use multiple CPUs instead of a GPU. 

In the medium term, I would like to move some tasks to AWS Batch in order to speed up the whole pipeline. 

Hope these answers are helpful! Any feedback and thoughts would be much appreciated! I've got a couple of questions on paper2code:
- What's the source of the academic documents?
- The split between tasks and subjects on the left side panel is neat. How do you do this? 

Best,
Kostas

**Comment by ghost** [comment]
Hi,

Thanks for your reply and hope you are all well !

I ll reply to your key questions by quoting them.

## What's the source of the academic documents?
I crawl several sources and here is the breakdown.
![Screenshot 2020-08-05 at 14 57 06](https://user-images.githubusercontent.com/56916043/89415310-fc056900-d72b-11ea-99ab-f096e8e9a715.png)

In a nutshell, ArXiv is the main source and I inspired my scraper from https://github.com/thibaultdalmon/pandor

I create several spiders with multiple regexes in golang.

## The split between tasks and subjects on the left side panel is neat. How do you do this?
For subjects, they are mainly the one from arxiv and for the tasks, it cannot be commented for now at least as work in progress... They are both used in the dynamic alert rss/newsletter system. 

## Do you think there's a use case for a search API?
Definitely, because I coded paper2code in golang and if I want to integrate search results from orion, I pretty much need that either it is gonna be too complicated to do the opposite.
Can you add some basic endpoints easily from your side ? at least for searching authors or papers.

For the credit page, I am working on the cms part of paper2code and will list some of the stacks I used for the website. I ll try to make something neat for the next mid-week.

Hope that I answered all your questions, and you can DM me whenever you want.

Thanks again for this great work that's Orion project.

Cheers,
X

**Comment by ghost** [comment]
Btw, yesterday ArXiv released its dataset on Kaggle.

Refs:
- https://twitter.com/arxiv/status/1291007439953973249?s=12
- https://www.kaggle.com/Cornell-University/arxiv
